### PR TITLE
Updated Reveal.js to latest release (3.2.0)

### PR DESCRIPTION
**Pull request by lgautier**
(also added Reveal.js's LICENSE)

### CODE REVIEW

**Comment by ramereth** [comment]
Works for me :+1:

**Comment by jcockhren** [comment]
I'd like this to included in the next release if possible. :smile: 

@tell-k

**Comment by return42** [comment]
FWIW: in my fork I upgraded to Reveal 3.4.1 and jQuery 3.2.0 see commits at: https://github.com/return42/sphinxjp.themes.revealjs/commits/master

@tell-k : may you like to cherry pick some patches of my patch series ... or if you prefer, ask me for PR of the full series. If you have no more time to work on  sphinxjp.themes.revealjs its OK, a short info would be nice / what ever, I want to say: Thanks for your great work which is a inspiration!

**Comment by tell-k** [comment]
@lgautier  Thanks for your help. Sorry too late my reply.

**Comment by lgautier** [comment]
Thanks for writing the theme and sharing it in the first place. 

Reveal.js is now at release 3.6.0, I think. I have not tried how well the PR is holding up.

**Pull request merged**
